### ISSUE TITLE
Bug: Check rejecting URL due to file size

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit.planning.data.gov.uk#180]
An LPA is looking to validate their data using the check tool, but told that their data is exceeding file size limits. Their data is below this limit

**What were you expecting to see:**

The next page in the Check service (file being checked

**What are you seeing:**

An error that the file size exceeds limits

**Who raised it**

Leicester City
Ashford Borough Council

**Problem causing**

The LPA cannot validate their endpoints or submit it to the Data Management team

**URL Leicester City**
- https://geoserver.leicester.gov.uk/geoserver/CONSAREAS/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=CONSAREAS%3AODP_CONSAREAS&maxFeatures=50&outputFormat=application%2Fjson

**URL Ashford Borough Council**
- https://www.ashford.gov.uk/planning-and-development/works-to-trees-and-hedges/tree-preservation-orders/
- https://www.ashford.gov.uk/media/uuqnswra/tpo_spatial_22_07_24.csv

**Comment by rosado** [comment]
The statement "their data is below the limit" is incorrect for Ashford Borough Council - it's well above 10 megs. 

The other dataset seems to work on 'main' branch as of now (the dataset has errors, but uploads fine when tested locally).
