### ISSUE TITLE
Update code to have it generate an email using a mail to link

### ISSUE THREAD

**Issue by GeorgeGoodall** [digital-land/submit.planning.data.gov.uk#214]
As GovUk Notify and Jira dont seem to work well together, and also we aren't allowed to use the Jira API. we have decided to fall back on to a mail to link at the end of the endpoint submission form. 

after completing the form, a mail to link should be presented that opens the users mail client with the email already written out

**Comment by GeorgeGoodall** [comment]
@alextea @gwencariad 

Hey Alex/Gwen

I've implemented the code to generate the mail to link, but I imagine you will want to rewrite the content at the end of the endpoint submission form

currently, I've just quickly chucked this link in on the confirmation page at the very end:

![Image](https://github.com/user-attachments/assets/27bf3390-86d6-4ec1-917b-23c7abab54a9)

I'm not sure if you want it here, or on the previous check-answers page? and also I imagine you want the content changing wherever it goes. 

the mail to link currently opens the following email:

![Image](https://github.com/user-attachments/assets/384c8966-2544-4240-96bc-1b044a3507e4)

Can you have a think about this, and let me know how you think we should update the page content / email content if needed?

also, I have made a ticket to add in the email content on the page with a copy to clipboard button so if for whatever reason the organisation can't use the mail to link, they can manually copy the email and enter it into a browser based mail client or other

thanks

George

cc: @Darren-CheckPlanningData @CharliePatterson

**Comment by GeorgeGoodall** [comment]
Talking with Charlie some more, he wants to go ahead with the mailTo or copy to clipboard option on this. we outlined three possibilities

1. On the 'check your answers' page, rather than the CTA button being 'submit dataset' and taking you to the next page, to wire in the 'mailto:' link there.
2. On the step-by-step page, change the copy to just include instructions on what they need to do to mail the endpoint (so, not to link to the form in this instance).
3. On the 'check your answers' page, change the button to be 'continue', and change the copy on the final page to include the mailto link as the main thing, and a backup of 'copy/paste' instructions


I would vote we go for option 3.

either way, we need designs input on this, and some content writing for these pages. 

I will move this ticket back to the sprint backlog for now, and @alextea and @gwencariad can pick it up once alex is back this week.

cc: @CharliePatterson @Darren-CheckPlanningData

**Comment by CharliePatterson** [comment]
We've opted for this approach as an interim solution until we're able to properly integrate with Jira: https://github.com/digital-land/submit.planning.data.gov.uk/issues/312
