### ISSUE TITLE
Spike: BFL checks/pipeline. Ensuring these are built in to service

### ISSUE THREAD

**Issue by paris-dp** [digital-land/submit.planning.data.gov.uk#219]
What
We would like to ensure that the providers service and pipeline can support data providers (LPAs) in providing accurate data which conforms to data standards. As Brownfield Land data is mandated, we would like the service to include this. 

Problem
We would like to understand current validation and if the scope of current providers service (check) needs to be expanded to include the validation of the brownfield land checker. Data providers may run 'check' on brownfield land data and it may not include validation specific to brownfield land. 

Dependencies
Infrastructure team to explore what validation currently exists for BFL on the platform

Tasks

- [ ] Reach out to Infrastructure team to find out what the validation is currently for BFL checking
- [ ] Paris to attend meeting with Infrastructure if required

**Comment by CharliePatterson** [comment]
The work for this should now be covered in other tickets, closing.
