### ISSUE TITLE
Add additional datasets to the check service

### ISSUE THREAD

**Issue by GeorgeGoodall** [digital-land/submit.planning.data.gov.uk#230]
## Context

The LPA dashboard will show the 15 datasets that LPAs are being asked to provide (the 8 datasets that have been mandated via the ODP program, and 7 additional datasets).

However, the check service only currently accepts the 8 datasets, and so we need to expand the scope of this to be able to accept and check/validate the additional 7 datasets.

The additional data sets are listed here:
[https://datasette.planning.data.gov.uk/digital-land?sql=select%0D%0A++d.name%2C%0D%0A++d.dat[…]pen-standard%27%2C%0D%0A++++%27piloting%27%0D%0A++%29](https://datasette.planning.data.gov.uk/digital-land?sql=select%0D%0A++d.name%2C%0D%0A++d.dataset%2C%0D%0A++s.specification%2C%0D%0A++specification_status%0D%0Afrom%0D%0A++dataset+d%0D%0A++LEFT+JOIN+specification_dataset+sd+ON+d.dataset+%3D+sd.dataset%0D%0A++LEFT+JOIN+specification+s+ON+sd.specification+%3D+s.specification%0D%0AWHERE%0D%0A++specification_status+in+%28%0D%0A++++%27candidate-standard%27%2C%0D%0A++++%27open-standard%27%2C%0D%0A++++%27piloting%27%0D%0A++%29)
This is also what Swati will need to identify the fields that Infrastructure team would use to add to the database?

Samriti has informed us that in theory all datasets should work - except brownfield land, which we're unsure about. We should add the additional datasets and test to see if this is the case.

## Questions: 

- What datasets should we add? @CharliePatterson (should we just add all the datasets?)
- How should we change the design of the dataset selection page? @alextea (should we use the same pattern as the org finder?)
- Who will test the datasets once this update it on dev? @CharliePatterson @paris-dp @MJFaucherFolie 

Dependency with Infrastructure[
https://trello.com/c/QcK5OASf

**Comment by CharliePatterson** [comment]
Thanks 🙏  just to clarify:

We think that all 15 datasets should work with the check tool (i.e. that it will perform the necessary validation checks and return the right information) - but, we'd need to add them in and check on dev env to see if they'll work?

The preference would be to add all 15 datasets, if we're confident that there aren't any additional checks that are required - has somebody tested this assumption?

If we find that any of the datasets don't work with the check tool (and substantially more work would be required to get the tool to work with them), then we'd need an interim solution - e.g. removing those datasets from the LPA dashboard page.

As for your question around testing - yup, we can tackle that. @MJFaucherFolie would you be able to help with sourcing files that we could use for testing?

**Comment by alextea** [comment]
Long term solution for dataset selection is that we would deep link into the check service flow and it would already know the LPA and dataset.

Short term I think we could just add more radio buttons.

**Comment by GeorgeGoodall** [comment]
@CharliePatterson as discussed yesterday, there's more than 15 datasets. 
for now I'm going to use all those in the previsions table:  https://datasette.planning.data.gov.uk/digital-land?sql=select+DISTINCT+p.dataset%2C+d.name%0D%0Afrom+provision+p%0D%0ALEFT+JOIN+dataset+d+ON+p.dataset+%3D+d.dataset

@alextea this comes out to 51 datasets in total. we might need to change away from radios

**Comment by GeorgeGoodall** [comment]
pushed initial additions to https://check.development.digital-land.info/

@paris-dp is going to have a look

**Comment by GeorgeGoodall** [comment]
list of datasets to check can maybe be pulled from here. going to speak with col

https://datasette.planning.data.gov.uk/digital-land/specification

**Comment by MJFaucherFolie** [comment]
@GeorgeGoodall Happy to help. Going to try and pull files from https://www.planning.data.gov.uk/dataset/ into something we can test. Will keep you updated on progress

**Comment by MJFaucherFolie** [comment]
Created a folder containing files to test the the Check service in Sharepoint: https://mhclg-my.sharepoint.com/:f:/g/personal/mj_faucher-folie_communities_gov_uk/EoLdIQkvsKhIuwL7H5QsGP4BI2_7Ka8p32Pnp2w75fMRJQ?e=T0Podu

Also drafted a spreadsheet to help keep track: https://mhclg-my.sharepoint.com/:x:/g/personal/mj_faucher-folie_communities_gov_uk/Edft5AO0LeVIuSmTyRUPCB0BDbMMfzh90iKqrwjROHbw_Q?e=ZAvGRi

Conversation with George highlighted that previous testing of the Check service used 1 okay file and 1 or 2 error files for each dataset

**Comment by MJFaucherFolie** [comment]
Added bad data to the [Sharepoint ](https://mhclg-my.sharepoint.com.mcas.ms/my?id=%2Fpersonal%2Fmj%5Ffaucher%2Dfolie%5Fcommunities%5Fgov%5Fuk%2FDocuments%2FData%20to%20test)for the following datasets:

- Brownfield land
- Developer agreement contribution
- Developer agreement transaction
- Developer agreement
- Infrastructure funding statement

The modifications made to the files are stored in the [spreadsheet](https://mhclg-my.sharepoint.com/:x:/g/personal/mj_faucher-folie_communities_gov_uk/Edft5AO0LeVIuSmTyRUPCB0BDbMMfzh90iKqrwjROHbw_Q?e=IQTjYg&nav=MTVfezJCQThENDkyLURGOTEtNDZFMy1CQTE5LUQ0RUQ3RjcyNzU5Qn0): https://mhclg-my.sharepoint.com/:x:/g/personal/mj_faucher-folie_communities_gov_uk/Edft5AO0LeVIuSmTyRUPCB0BDbMMfzh90iKqrwjROHbw_Q?e=IQTjYg&nav=MTVfezJCQThENDkyLURGOTEtNDZFMy1CQTE5LUQ0RUQ3RjcyNzU5Qn0

**Comment by Ben-Hodgkiss** [comment]
@Darren-CheckPlanningData - can you confirm exactly what you need Infrastructure to do on this ticket? Is it just allowing the Check tool to process the other datasets with no other changes? Or are there more fundamental changes we need to make to allow it to process? Can you also confirm what isn't working right now - what screens do you see etc?

**Comment by GeorgeGoodall** [comment]
Going to spend 15 mins to see if the map issue is an easy fix

**Comment by GeorgeGoodall** [comment]
Testing this brownfield land: https://datasette.planning.data.gov.uk/digital-land?sql=select+organisation%2C+name%2C+endpoint_url%2C+status+from+reporting_latest_endpoints+WHERE+pipeline+%3D+%27brownfield-land%27

results: https://check.development.digital-land.info/results/ErBjNqLXhqKAgwW6bdXtjo/0

as the geometries are stored across two columns GeoX and GeoY. the map doesn't load properly

for now ill add a fix in to hide the map when this happens but we may need to look at this for future files

**Comment by CharliePatterson** [comment]
Closing this ticket - initial focus will be on brownfield land. I'll make sure we've got the appropriate tickets in to cover that work.
