### ISSUE TITLE
Spike:  Options/proposal for the content of the page

### ISSUE THREAD

**Issue by Darren-CheckPlanningData** [digital-land/submit.planning.data.gov.uk#258]
Questions to answer:

- [x] Options/proposal for the content of the page: it would be good to get something together for testing, to see if we can improve on what we have. I think there's probably short term and long term approaches here - specifically, updating the copy in the short term, and then a longer term overhaul of the page to make it more like a traditional landing page.

**Comment by paris-dp** [comment]
Thoughts and reflections around this. First small changes discussed with Gwen. Longer term/working towards below. Further work needed to split out tasks/priorities.




![Image](https://github.com/user-attachments/assets/9f1f7e81-5769-4105-9bcc-518f7e138b25)

**Comment by paris-dp** [comment]
Moving this issue over to 'done' as spike/reflections around this are complete. New issues will be created for content added.
