### ISSUE TITLE
Tech Debt: Integration testing

### ISSUE THREAD

**Issue by Darren-CheckPlanningData** [digital-land/submit.planning.data.gov.uk#290]
## Why do we need to do this? (value)
Integration testing ensures individual components work together seamlessly, catching errors that unit testing may miss. By testing interactions between components, integration testing identifies and fixes issues early, preventing costly rework and delays, and resulting in more reliable and stable software.

## Problem Statement
We have been developing these new pages in a hurry to meet imposed deadlines. this had lead us to skip the development of integration tests. these should now be added in so we can maintain are velocity of work and reduce the risk of introducing future bugs

## Acceptance criteria
- high integration test coverage of new controller, views and utility functions
- fast execution of tests to avoid excessive cicd run times
- testing should be written using jsdocs

### Write acceptance tests for the code paths that render the following
- [x] #323
- [x] #324
- [x] #325
- [ ]  Issue details page
- [ ]  Endpoint errors page
- [ ]  Submit pages

**Comment by GeorgeGoodall** [comment]
Going to split this up into subtickets

**Comment by GeorgeGoodall** [comment]
Have split this up into subtickets, going to archive this
