### ISSUE TITLE
Bug: Missing tech guidance link on conservation area page

### ISSUE THREAD

**Issue by Darren-CheckPlanningData** [digital-land/submit.planning.data.gov.uk#309]
Problem:
Greg Slater
  10:00 AM - 21/08/24
Morning  I just noticed that the [conservation area guidance page](https://www.planning.data.gov.uk/guidance/specifications/conservation-area) seems to be missing the link at the top to the technical guidance :eyes:
(see attached A4D guidance pic for comparison)

 

![Image](https://github.com/user-attachments/assets/ffd183ec-c282-4fec-8d90-088334f97138)

### A4D guidance pic
![Image](https://github.com/user-attachments/assets/89c31066-77cb-4052-b9f8-eb6dc6b12c07)

**Comment by stevenjmesser** [comment]
Raised in error
