### ISSUE TITLE
Fix link to live data

### ISSUE THREAD

**Issue by GeorgeGoodall** [digital-land/submit.planning.data.gov.uk#322]
# Problem statement
this link to live data is pointing to the wrong place:
https://check.planning.data.gov.uk/organisations/local-authority:NBL/article-4-direction-area

**Comment by GeorgeGoodall** [comment]
@CharliePatterson 

Samriti has highlighted this bug for us to fix, shouldn't take too long so I've added it to this sprint.

**Comment by CharliePatterson** [comment]
@GeorgeGoodall there's a duplicate open for this with more detail - closing this one in favour of the other: https://github.com/digital-land/submit.planning.data.gov.uk/issues/321
